labelType: long
buildStyle:
  bold: true
  foreground: "#f7bf23"
startStyle:
  foreground: "#bfbbbb"
passStyle:
  foreground: "#56a36e"
failStyle:
  bold: true
  foreground: "#bd1919"
skipStyle:
  foreground: "#638196"
passPackageStyle:
  foreground: "#56a36e"
  hide: false
failPackageStyle:
  bold: true
  foreground: "#bd1919"
coverThreshold: 80
coveredStyle:
  foreground: "#3f8f22"
uncoveredStyle:
  bold: true
  foreground: "#deaa18"
fileStyle:
  foreground: "#9c9c9c"
lineStyle:
  foreground: "#858181"
