require("uno.plugins")
require("uno.config")
require("uno.lushTheming")
require("uno.lualine.evil")
require("uno.lsp")
require("uno.neoformat")
require("uno.comment")
require("uno.colorizer")
require("uno.dressing")
require("uno.fileTree")
require("uno.telescope")
require("uno.treesitter")
require("uno.zenmode")
require("uno.bufferline")
require("uno.keybindings") -- #FFF #F0E
require("uno.icons")
require("uno.gitsigns")
require("uno.terminal")
require("uno.diffview")
require("uno.notify")
require("uno.luasnip")

-- WHY DOESN"T THIS FUCKEN WORK
-- require("uno.quickfix")

-- require("uno.statusline")
-- require("uno.modes")
