require("uno.lazy")
-- require("uno.plugins")
require("uno.config")
require("uno.lushTheming")
require("uno.notify")
require("uno.keybindings")
require("uno.navigator")
require("uno.lsp")
require("uno.neoformat")
require("uno.comment")
require("uno.colorizer")
require("uno.dressing")
require("uno.filetree")
require("uno.telescope")
require("uno.treesitter")
require("uno.zenmode")
require("uno.bufferline")
require("uno.highlights")
require("uno.icons")
require("uno.gitsigns")
require("uno.terminal")
require("uno.diffview")
require("uno.luasnip")
require("uno.trouble")
require("uno.workspaces")
require("uno.symbols")
require("uno.aerial")
require("uno.codewindow")
require("uno.quickfix")
require("uno.heirline.heirline")
-- require("uno.lualine.evil")
require("uno.windows")
-- require("uno.neotest")

-- Experimental
-- require("uno.sidebar")

-- require("uno.statusline")
require("uno.modes")
