-- Don't like this plugin
-- require("sidebar-nvim").setup({
-- 	disable_default_keybindings = 0,
-- 	bindings = nil,
-- 	open = false,
-- 	side = "left",
-- 	initial_width = 50,
-- 	hide_statusline = false,
-- 	update_interval = 1000,
-- 	sections = { "files", "git", "symbols", "diagnostics", "todos" },
-- 	section_separator = { "", "--------------------", "" },
-- 	section_title_separator = { "" },
-- 	datetime = {
-- 		icon = "",
-- 		format = "%a %b %d, %H:%M",
-- 		clocks = {
-- 			{ name = "local" },
-- 		},
-- 	},
-- 	files = {
-- 		icon = "",
-- 		show_hidden = false,
-- 		ignored_paths = { "%.git$" },
-- 	},
-- 	-- containers = {
-- 	-- 	attach_shell = "/bin/zsh",
-- 	-- 	show_all = true,
-- 	-- 	interval = 5000,
-- 	-- },
-- 	git = {
-- 		groups_initially_closed = true,
-- 	},
-- 	todos = {
-- 		icon = "",
-- 		ignored_paths = { "~" }, -- ignore certain paths, this will prevent huge folders like $HOME to hog Neovim with TODO searching
-- 		initially_closed = false, -- whether the groups should be initially closed on start. You can manually open/close groups later.
-- 	},
-- })
