require("uno.config")
require("uno.plugins")
require("uno.lsp")
require("uno.impatient")
require("uno.comment")
require("uno.colorizer")
require("uno.dressing")
require("uno.fileTree")
require("uno.telescope")
require("uno.treesitter")
require("uno.zenmode")
require("uno.bufferline")
require("uno.keybindings") -- #FFF #F0E
require("uno.icons")
require("uno.gitsigns")
require("uno.terminal")
require("uno.lushTheming")
require("uno.diffview")
require("uno.notify")
-- require("uno.modes")
